
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-8
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-8
pull_requests: [{"author":{"id":"U_kgDOB3DoXA","is_bot":false,"login":"TheRealAndrxw","name":"Andrew Vosgueritchian"},"headRefName":"AV-UCSBDiningCommonsMenuItem-Fixtures","number":73,"title":"Av ucsb dining commons menu item fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/73"},{"author":{"id":"U_kgDOB3DoXA","is_bot":false,"login":"TheRealAndrxw","name":"Andrew Vosgueritchian"},"headRefName":"AV-UCSBDiningCommonsMenuItem-Backend","number":72,"title":"AV-UCSBDiningCommonsMenuItem Backend Crud","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/72"},{"author":{"id":"MDQ6VXNlcjQzMDE2ODM5","is_bot":false,"login":"KarstenLansing","name":"Karsten James Lansing"},"headRefName":"kl-RecommendationRequestsFormComponent","number":71,"title":"Kl recommendation requests form component","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/71"},{"author":{"id":"MDQ6VXNlcjQyMTYwOTky","is_bot":false,"login":"xinyao-song","name":"XinYao Song"},"headRefName":"xs-MIR_Fixtures","number":70,"title":"Create fixtures for MenuItemReview","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/70"},{"author":{"id":"MDQ6VXNlcjQyMTYwOTky","is_bot":false,"login":"xinyao-song","name":"XinYao Song"},"headRefName":"xs-CRUD_API","number":69,"title":"Copy files for Backend CRUD API MenuItemReview from team02","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/69"}]
