
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-8
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-8
pull_requests: [{"author":{"id":"MDQ6VXNlcjQzMDE2ODM5","is_bot":false,"login":"KarstenLansing","name":"Karsten James Lansing"},"headRefName":"kl-h05","number":119,"title":"KL-h05, Added RecommendationRequest Integration Tests ","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/119"},{"author":{"id":"U_kgDOBcwBsg","is_bot":false,"login":"bradygin","name":"Brady Gin"},"headRefName":"bg-h05","number":118,"title":"bg - h05, Added UCSBOrganization Integration Tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/118"}]
