
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-8
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-8
pull_requests: [{"author":{"id":"MDQ6VXNlcjQyMTYwOTky","is_bot":false,"login":"xinyao-song","name":"XinYao Song"},"headRefName":"xs-CRUD_API","number":69,"title":"Copy files for Backend CRUD API MenuItemReview from team02","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/69"},{"author":{"id":"MDQ6VXNlcjQzMDE2ODM5","is_bot":false,"login":"KarstenLansing","name":"Karsten James Lansing"},"headRefName":"kl-RecommendationRequestsFixtures","number":68,"title":"Added Recommendation requests fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/68"},{"author":{"id":"U_kgDOB00C0g","is_bot":false,"login":"spark686","name":""},"headRefName":"sp-Articles-backend","number":67,"title":"Added backend API routes for CRUD operations for ARTICLE","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/67"},{"author":{"id":"MDQ6VXNlcjQzMDE2ODM5","is_bot":false,"login":"KarstenLansing","name":"Karsten James Lansing"},"headRefName":"kl-CRUDFromTeam03RecommendationRequests","number":66,"title":"Added Backend API routes for CRUD operations for RecommendationRequest","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/66"}]
