
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-8
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-8
pull_requests: [{"author":{"id":"U_kgDOBdCSgA","is_bot":false,"login":"Hannahshakouri01","name":"Hannah Shakouri"},"headRefName":"hs-HelpRequest-Fixture","number":80,"title":"hs- Create fixtures for HelpRequest","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/80"},{"author":{"id":"U_kgDOBcwBsg","is_bot":false,"login":"bradygin","name":"Brady Gin"},"headRefName":"bg-UCSBOrganization-form-component","number":79,"title":"UCSBOrganization Form Component and its tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/79"},{"author":{"id":"MDQ6VXNlcjQyMTYwOTky","is_bot":false,"login":"xinyao-song","name":"XinYao Song"},"headRefName":"xs-MIR_Form","number":78,"title":" Form Component for MenuItemReview plus tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/78"},{"author":{"id":"U_kgDOBcwBsg","is_bot":false,"login":"bradygin","name":"Brady Gin"},"headRefName":"bg-UCSBOrganization-fixtures","number":77,"title":"bg - Added UCSBOrganization Fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/77"},{"author":{"id":"U_kgDOBcwBsg","is_bot":false,"login":"bradygin","name":"Brady Gin"},"headRefName":"bg-UCSBOrganization-backend","number":76,"title":"bg - Added legacy backend code","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/76"},{"author":{"id":"U_kgDOBdCSgA","is_bot":false,"login":"Hannahshakouri01","name":"Hannah Shakouri"},"headRefName":"hs-HelpRequest-backend","number":75,"title":"hs- Copy files for Backend HelpRequest from team02","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/75"},{"author":{"id":"U_kgDOB00C0g","is_bot":false,"login":"spark686","name":""},"headRefName":"sp-Articles-fixtures","number":74,"title":"sp - Create Articles Fixtures file","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/74"},{"author":{"id":"MDQ6VXNlcjQzMDE2ODM5","is_bot":false,"login":"KarstenLansing","name":"Karsten James Lansing"},"headRefName":"kl-RecommendationRequestsFormComponent","number":71,"title":"Kl recommendation requests form component","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/71"}]
