
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-8
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-8
pull_requests: [{"author":{"id":"U_kgDOBdCSgA","is_bot":false,"login":"Hannahshakouri01","name":"Hannah Shakouri"},"headRefName":"hs-HelpRequest-Create","number":114,"title":"hs- help request create page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/114"},{"author":{"id":"U_kgDOBcwBsg","is_bot":false,"login":"bradygin","name":"Brady Gin"},"headRefName":"bg-UCSBOrganization-indexPage","number":112,"title":"bg - ucsb organization index page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/112"},{"author":{"id":"U_kgDOBcwBsg","is_bot":false,"login":"bradygin","name":"Brady Gin"},"headRefName":"bg-UCSBOrganization-createPage","number":111,"title":"bg - ucsb organization create page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/111"},{"author":{"id":"U_kgDOBdCSgA","is_bot":false,"login":"Hannahshakouri01","name":"Hannah Shakouri"},"headRefName":"hs-HelpRequest-Placeholder","number":110,"title":"Hs help request placeholder","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-8/pull/110"}]
